name: PAGASA Monitor

on:
  schedule:
    # every 15 minutes at :07, :22, :37, :52 Manila (avoiding high-load times)
    - cron:  '7  * * * *'
    - cron:  '22 * * * *'
    - cron:  '37 * * * *'
    - cron:  '52 * * * *'

  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for committing updates to previous_data.json

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PAGASA monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        cd src
        python main.py

    - name: Commit and push updated data file
      run: |
        cd src
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add previous_data.json
        git commit -m "Update previous_data.json" || echo "No changes to commit"
        git pull --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
