name: PAGASA Monitor

on:
  schedule:
    # Explicitly run every 20 minutes at :10, :30, and :50 of every hour
    - cron: '10 0 * * *'
    - cron: '30 0 * * *'
    - cron: '50 0 * * *'
    - cron: '10 1 * * *'
    - cron: '30 1 * * *'
    - cron: '50 1 * * *'
    - cron: '10 2 * * *'
    - cron: '30 2 * * *'
    - cron: '50 2 * * *'
    - cron: '10 3 * * *'
    - cron: '30 3 * * *'
    - cron: '50 3 * * *'
    - cron: '10 4 * * *'
    - cron: '30 4 * * *'
    - cron: '50 4 * * *'
    - cron: '10 5 * * *'
    - cron: '30 5 * * *'
    - cron: '50 5 * * *'
    - cron: '10 6 * * *'
    - cron: '30 6 * * *'
    - cron: '50 6 * * *'
    - cron: '10 7 * * *'
    - cron: '30 7 * * *'
    - cron: '50 7 * * *'
    - cron: '10 8 * * *'
    - cron: '30 8 * * *'
    - cron: '50 8 * * *'
    - cron: '10 9 * * *'
    - cron: '30 9 * * *'
    - cron: '50 9 * * *'
    - cron: '10 10 * * *'
    - cron: '30 10 * * *'
    - cron: '50 10 * * *'
    - cron: '10 11 * * *'
    - cron: '30 11 * * *'
    - cron: '50 11 * * *'
    - cron: '10 12 * * *'
    - cron: '30 12 * * *'
    - cron: '50 12 * * *'
    - cron: '10 13 * * *'
    - cron: '30 13 * * *'
    - cron: '50 13 * * *'
    - cron: '10 14 * * *'
    - cron: '30 14 * * *'
    - cron: '50 14 * * *'
    - cron: '10 15 * * *'
    - cron: '30 15 * * *'
    - cron: '50 15 * * *'
    - cron: '10 16 * * *'
    - cron: '30 16 * * *'
    - cron: '50 16 * * *'
    - cron: '10 17 * * *'
    - cron: '30 17 * * *'
    - cron: '50 17 * * *'
    - cron: '10 18 * * *'
    - cron: '30 18 * * *'
    - cron: '50 18 * * *'
    - cron: '10 19 * * *'
    - cron: '30 19 * * *'
    - cron: '50 19 * * *'
    - cron: '10 20 * * *'
    - cron: '30 20 * * *'
    - cron: '50 20 * * *'
    - cron: '10 21 * * *'
    - cron: '30 21 * * *'
    - cron: '50 21 * * *'
    - cron: '10 22 * * *'
    - cron: '30 22 * * *'
    - cron: '50 22 * * *'
    - cron: '10 23 * * *'
    - cron: '30 23 * * *'
    - cron: '50 23 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for committing updates to previous_data.json

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PAGASA monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        cd src
        python main.py

    - name: Commit and push updated data file
      run: |
        cd src
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add previous_data.json
        git commit -m "Update previous_data.json" || echo "No changes to commit"
        git pull --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
